server:
  port: 8888
  tomcat:
    # Tomcat的header缓冲区大小
    max-http-header-size: 8192
  servlet:
    context-path: /swagger

# 日志配置
logback:
  appName: swagger
  # 服务器
  # dir: /home/deploy/ab/logs
  # 本地
  dir: /Users/chaoxy/Downloads/logs

# http://127.0.0.1:8888/swagger/swagger-ui.html
# Swagger UI 页面:  http://server:port/context-path/swagger-ui.html
# OpenAPI JSON 格式文档 : http://server:port/context-path/v3/api-docs
# yaml 格式文档  路径：/v3/api-docs.yaml
# swagger3
springdoc:
  # swagger-ui custom path
  swagger-ui:
    # 禁用 swagger-ui
    # enabled: false
    path: /swagger-ui.html
  # /api-docs endpoint custom path
  api-docs:
    path: /api-docs
    # 禁用 springdoc-openapi 端点（默认为 /v3/api-docs）
    # enabled: false
  # 指定接口包列表扫描，多个以英文逗号分隔
  # packagesToScan: com.cxy.swagger.controller
  # 指定访问接口路径列表扫描，多个以英文逗号分隔
  # pathsToMatch: /api/**, /admin/**

